version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:latest
    environment:
      report_duration: <<pipeline.parameters.duration>>
    steps:
      - checkout
      - run: |
          bash resolution_time.bash
      - store_artifacts:
          path: ./closed_durations.json
          destination: summary



workflows:
  version: 2
  adhoc:
    when: <<pipeline.parameters.adhoc>>
    jobs:
      - build
  nightly:
    triggers:
     - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

parameters:
  adhoc:
    type: boolean
    default: false
  duration:
    type: string
    default: "-1 week"